name = "workers-airtable-form"
compatibility_date = "2022-07-10"
main = "src/index.js"

account_id = "7e9cce172cc3bcfb56a2981822417382"
workers_dev = true

[vars]
AIRTABLE_BASE_ID = "app550XiQNw3CZRnA"
AIRTABLE_TABLE_NAME = "Form Submissions"
FORM_URL = "https://workers-airtable-form-8y2.pages.dev/"
